# Generated by Django 3.2.8 on 2021-12-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeedingTemperature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Temperatura de alimentación',
                'verbose_name_plural': 'Temperaturas de alimentación',
            },
        ),
        migrations.CreateModel(
            name='FeedConductivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Conductividad de alimentación',
                'verbose_name_plural': 'Conductividades de alimentación',
            },
        ),
        migrations.CreateModel(
            name='feedPressure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Presión de alimentación',
                'verbose_name_plural': 'Presiones de alimentación',
            },
        ),
        migrations.CreateModel(
            name='PermeateConductivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Conductividad de permeado',
                'verbose_name_plural': 'Conductividades de permeado',
            },
        ),
        migrations.CreateModel(
            name='PermeateFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Caudal de permeado',
                'verbose_name_plural': 'Caudales de permeado',
            },
        ),
        migrations.CreateModel(
            name='RejectFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Caudal de rechazo',
                'verbose_name_plural': 'Caudales de rechazo',
            },
        ),
        migrations.CreateModel(
            name='rejectionPressure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Presión de rechazo',
                'verbose_name_plural': 'Presiones de rechazo',
            },
        ),
    ]
