# Generated by Django 3.2.8 on 2022-03-29 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20220311_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductivityPermeateMembranes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('time', models.DateTimeField(verbose_name='Fecha')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Conductividad de permeado de membranas',
                'verbose_name_plural': 'Conductividades de permeado de membranas',
            },
        ),
        migrations.CreateModel(
            name='ConductivityPermeateVessels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('time', models.DateTimeField(verbose_name='Fecha')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Conductividad de permeado de vasijas',
                'verbose_name_plural': 'Conductividades de permeado de vasijas',
            },
        ),
        migrations.CreateModel(
            name='FeedPressureVessels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('time', models.DateTimeField(verbose_name='Fecha')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Presión de alimentación de vasijas',
                'verbose_name_plural': 'Presiones de alimentación de vasijas',
            },
        ),
        migrations.CreateModel(
            name='FeedTemperature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('time', models.DateTimeField(verbose_name='Fecha')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Temperatura de alimentación',
                'verbose_name_plural': 'Temperaturas de alimentación',
            },
        ),
        migrations.CreateModel(
            name='MembraneFeedPressure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('time', models.DateTimeField(verbose_name='Fecha')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Presión de alimentación de membranas',
                'verbose_name_plural': 'Presiones de alimentación de membranas',
            },
        ),
        migrations.CreateModel(
            name='MembranePermeateFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('time', models.DateTimeField(verbose_name='Fecha')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Caudal de permeado de membranas',
                'verbose_name_plural': 'Caudales de permeado de membranas',
            },
        ),
        migrations.CreateModel(
            name='MembraneRejectionFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('time', models.DateTimeField(verbose_name='Fecha')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Caudal de rechazo de membranas',
                'verbose_name_plural': 'Caudales de rechazo de membranas',
            },
        ),
        migrations.CreateModel(
            name='MembraneRejectionPressure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('time', models.DateTimeField(verbose_name='Fecha')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Presión de rechazo de membranas',
                'verbose_name_plural': 'Presiones de rechazo de membranas',
            },
        ),
        migrations.CreateModel(
            name='RegisterMembranes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('register', models.BooleanField()),
                ('time', models.DateTimeField(verbose_name='Fecha')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Registro de membranas',
                'verbose_name_plural': 'Registros de membranas',
            },
        ),
        migrations.CreateModel(
            name='RegisterVessels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('register', models.BooleanField()),
                ('time', models.DateTimeField(verbose_name='Fecha')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Registro de vasijas',
                'verbose_name_plural': 'Registros de vasijas',
            },
        ),
        migrations.CreateModel(
            name='RejectPressureVessels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('time', models.DateTimeField(verbose_name='Fecha')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Presión de rechazo de vasijas',
                'verbose_name_plural': 'Presiones de rechazo de vasijas',
            },
        ),
        migrations.CreateModel(
            name='VesselsFeedingFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('time', models.DateTimeField(verbose_name='Fecha')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Caudal de alimentación de vasijas',
                'verbose_name_plural': 'Caudales de alimentación de vasijas',
            },
        ),
        migrations.CreateModel(
            name='VesselsPermeateFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('time', models.DateTimeField(verbose_name='Fecha')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Flujo de permeado de vasijas',
                'verbose_name_plural': 'Flujos de permeado de vasijas',
            },
        ),
        migrations.DeleteModel(
            name='DeedingTemperature',
        ),
        migrations.DeleteModel(
            name='feedPressure',
        ),
        migrations.DeleteModel(
            name='PermeateConductivity',
        ),
        migrations.DeleteModel(
            name='PermeateFlow',
        ),
        migrations.DeleteModel(
            name='RejectFlow',
        ),
        migrations.DeleteModel(
            name='rejectionPressure',
        ),
        migrations.AddField(
            model_name='feedconductivity',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
