# Generated by Django 3.2.8 on 2022-03-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20220329_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductivitypermeatemembranes',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='conductivitypermeatevessels',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='feedconductivity',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='feedpressurevessels',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='feedtemperature',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='membranefeedpressure',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='membranepermeateflow',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='membranerejectionflow',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='membranerejectionpressure',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='registermembranes',
            name='time',
        ),
        migrations.RemoveField(
            model_name='registervessels',
            name='time',
        ),
        migrations.RemoveField(
            model_name='rejectpressurevessels',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='vesselsfeedingflow',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='vesselspermeateflow',
            name='unit',
        ),
    ]
