# Generated by Django 3.2.8 on 2022-03-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='action',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='actiondetection',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='actiondetection',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='actiondetection',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicalaction',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalaction',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicalactiondetection',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalactiondetection',
            name='date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='historicalactiondetection',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicalrisk',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalrisk',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
    ]
