# Generated by Django 3.2.8 on 2021-10-23 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identificationNFC', '0002_alter_identification_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identificationNFC.activemodel', verbose_name='Estado Autentificación NFC'),
        ),
    ]
