# Generated by Django 3.2.8 on 2022-01-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identificationNFC', '0003_alter_identification_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalidentification',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='identification',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
