# Generated by Django 3.2.8 on 2021-10-20 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identificationNFC', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='nfc',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='identificationNFC.identification', verbose_name='NFC'),
        ),
        migrations.AddField(
            model_name='user',
            name='nfc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='identificationNFC.identification', verbose_name='NFC'),
        ),
    ]
