# Generated by Django 3.2.8 on 2021-10-27 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identificationNFC', '0003_alter_identification_active'),
        ('users', '0002_auto_20211019_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nfc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='identificationNFC.identification', verbose_name='NFC'),
        ),
    ]
