# Generated by Django 3.2.8 on 2022-01-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identificationNFC', '0004_auto_20220112_1629'),
        ('users', '0003_alter_user_nfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nfc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identificationNFC.identification', verbose_name='NFC'),
        ),
    ]
