# Generated by Django 3.2.8 on 2022-06-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_nfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='image',
            field=models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='Imagen de perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/profile', verbose_name='Imagen de perfil'),
        ),
    ]
