# Generated by Django 3.2.8 on 2021-11-25 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricaldetectionPPE',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('helmet', models.BooleanField(verbose_name='Casco')),
                ('headphones', models.BooleanField(verbose_name='Audifonos')),
                ('goggles', models.BooleanField(verbose_name='Antiparras')),
                ('gloves', models.BooleanField(verbose_name='Guantes')),
                ('boots', models.BooleanField(verbose_name='Botas')),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario detectado')),
            ],
            options={
                'verbose_name': 'historical detecion PPE',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='detectionPPE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('helmet', models.BooleanField(verbose_name='Casco')),
                ('headphones', models.BooleanField(verbose_name='Audifonos')),
                ('goggles', models.BooleanField(verbose_name='Antiparras')),
                ('gloves', models.BooleanField(verbose_name='Guantes')),
                ('boots', models.BooleanField(verbose_name='Botas')),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario detectado')),
            ],
            options={
                'verbose_name': 'detecion PPE',
                'verbose_name_plural': 'detecciones PPE',
            },
        ),
    ]
