# Generated by Django 3.2.8 on 2021-11-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPE', '0002_alter_detectionppe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionppe',
            name='hour',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Hora'),
        ),
        migrations.AddField(
            model_name='historicaldetectionppe',
            name='hour',
            field=models.TimeField(blank=True, editable=False, null=True, verbose_name='Hora'),
        ),
    ]
