# Generated by Django 3.2.8 on 2022-03-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPE', '0003_auto_20211129_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionppe',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='historicaldetectionppe',
            name='hour',
        ),
        migrations.AddField(
            model_name='detectionppe',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='historicaldetectionppe',
            name='date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha'),
        ),
    ]
