# Generated by Django 3.2.8 on 2022-03-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPE', '0004_auto_20220311_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionppe',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='historicaldetectionppe',
            name='date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha'),
        ),
    ]
