# Generated by Django 3.2.8 on 2022-03-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPE', '0005_auto_20220311_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionppe',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='detectionppe',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicaldetectionppe',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicaldetectionppe',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
    ]
